### ISSUE TITLE
Right click to copy password flash back

### ISSUE THREAD

**Issue by xljabbber** [CodeDead/Advanced-PassGen#2] opened 2019-07-30 21:46 UTC

**Comment by CodeDead** [comment] 2019-07-31 00:51
Hi there,

Could you provide any more details or a description of the problem since we don't have much to go on by your title alone.

Thanks in advance

**Comment by xljabbber** [comment] 2019-08-01 12:56
https://streamable.com/4vw32
I uploaded the video, you see win101809 17763.107

**Comment by CodeDead** [comment] 2019-08-01 13:07
Thank you for the extensive video referencing the issue.

This seems to be related to a blocked clipboard. This can happen from time to time when dealing with the clipboard but we'll include a fix that will prevent this from crashing the application.

You can expect a fix for this issue in the next release. In the main time, make sure that any other running applications aren't misusing your clipboard because this is usually caused by another application that is not releasing the handle to the clipboard, especially if this happens all the time (might even be malware related).

**Comment by CodeDead** [comment] 2019-08-03 13:56
Hi,

Please try out the latest release. It should no longer crash to the desktop but feel free to re-open this issue if the problem persists.

Kind regards

**Closed by CodeDead** 2019-08-03 13:56 UTC
Labels: bug
