### ISSUE TITLE
Program crashes on Big input

### ISSUE THREAD

**Issue by 0x00Finch** [CodeDead/Advanced-PassGen#4] opened 2021-09-27 20:13 UTC
**Describe the bug**
Password Length cannot take big numbers.

**To Reproduce**
1. Go to General
2. Enter a length of 99999999
3. Click on List
4. Click on Generate
5. Then the program crashes

**Expected behavior**
Expected a catch of exception or generate exactly the length user entered.

**Screenshots**
None

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 21H1]
 - Version: [19043.1237]

**Additional context**
None

**Comment by CodeDead** [comment] 2021-09-28 14:18
Thanks for reporting this issue. I'll have a look and possibly release a new version if applicable.
It's been a while that this application has received some love, either way!

**Comment by 0x00Finch** [comment] 2021-09-29 03:11
Thank you for responding, cheers!

**Comment by DanExxed** [comment] 2022-10-02 16:35
This issue is caused by the fact that the program cannot handle a big input, this issue is very common, I am currently trying to fix this as it effects windows 10 specifically (from what i have done with it).

**Comment by CodeDead** [comment] 2022-10-04 20:48
@DanExxed I might rewrite this entire application in a different programming language altogether to get more performance out of it and additionally get rid of the .NET framework.

Something like Rust should do the trick. Do note that the maximum number is limited by CPU architecture and value type. E.g:
```
int.MaxValue: 2,147,483,647
```

**Comment by DanExxed** [comment] 2022-10-04 22:07
@CodeDead That is an amazing idea, I hope to see it happen one day.

**Comment by CodeDead** [comment] 2022-10-12 13:58
@DanExxed 
Something is brewing with React + Tauri (Rust backend):
![Screenshot from 2022-10-12 15-57-10](https://user-images.githubusercontent.com/16293330/195362822-9cdeb62e-0ad6-4701-81e5-a89c39bab95c.png)

This is a native gtk window that uses the system's webview which produces incredibly tiny binaries and the app will run on Linux, Windows and macOS.

**Comment by CodeDead** [comment] 2022-10-13 21:53
![Screenshot from 2022-10-13 23-52-53](https://user-images.githubusercontent.com/16293330/195717990-d0bf99da-64b0-4a39-8501-1189c94803b2.png)

**Comment by CodeDead** [comment] 2022-10-16 20:40
Alright this issue has been handled in PR https://github.com/CodeDead/Advanced-PassGen/pull/5 so I'm closing this. The fix will be available in the next release.

**Closed by CodeDead** 2022-10-16 20:40 UTC
Labels: bug
